# Generated by Django 3.1.2 on 2020-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WWHDapp', '0002_remove_category_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pic',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
