# Generated by Django 3.1.2 on 2020-11-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WWHDapp', '0007_auto_20201101_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WWHDapp.category'),
        ),
    ]
